### ISSUE TITLE
Add index mapping

### ISSUE THREAD

**Issue by danielveloso09** [ricardojcribeiro/schema_to_dbml#64]
### Problem

The current implementation does not map a tables indexes, which is an important information to know while looking into the diagram generated by DBML Docs. 

Schema example:
```ruby
  create_table "links" do |t|
    ...
    t.string "slug",
    ...
    t.index ["slug"], name: "index_links_on_slug", unique: true
  end
```

Expected generated dbml doc:
```
Table links {
  ...
  slug varchar
  ...
  indexes {
    slug [unique, name: 'index_links_on_slug']
  }
}
```

DBML Documentation: https://dbml.dbdiagram.io/docs/#index-definition

**Comment by danielveloso09** [comment]
@ricardojcribeiro,

While reviewing the necessary changes for our implementation, I noticed that the parsed_columns attribute, currently utilized in various sections of our codebase, represents more than just column definitions; it encapsulates the entire table definition, including both columns and indexes. To accurately reflect its broader scope, I suggest renaming it to a more fitting and descriptive name.

Here are a few potential alternatives:
- `table_attributes`
- `table_definition`
- Any other name that resonates with the purpose and content of the attribute

I believe renaming this attribute will enhance clarity and maintainability throughout our codebase. What are your thoughts on this matter?

**Comment by ricardojcribeiro** [comment]
@danielveloso09 This is a really good feature that we should have by default. Thanks for pointing this out!
